---
- hosts: web
  tasks:
    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080
    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted